# Main background, NULL = transparent
theme[main_bg]=""

# Main text color
theme[main_fg]="{{colors.on_surface.default.hex}}"

# Title color for boxes
theme[title]="{{colors.primary.default.hex}}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="{{colors.tertiary.default.hex}}"

# Background color of selected item in lists
theme[selected_bg]="{{colors.secondary_container.default.hex}}"

# Foreground color of selected item in lists
theme[selected_fg]="{{colors.on_secondary_container.default.hex}}"

# Color of inactive/disabled text
theme[inactive_fg]="{{colors.outline.default.hex}}"

# Misc colors for Process list icons, etc.
theme[proc_misc]="{{colors.secondary.default.hex}}"

# Cpu box outline color
theme[cpu_box]="{{colors.outline_variant.default.hex}}"

# Memory box outline color
theme[mem_box]="{{colors.outline_variant.default.hex}}"

# Net box outline color
theme[net_box]="{{colors.outline_variant.default.hex}}"

# Processes box outline color
theme[proc_box]="{{colors.outline_variant.default.hex}}"

# Box divider line color
theme[div_line]="{{colors.outline_variant.default.hex}}"

# Temperature graph colors
theme[temp_start]="{{colors.primary.default.hex}}"
theme[temp_mid]="{{colors.tertiary.default.hex}}"
theme[temp_end]="{{colors.error.default.hex}}"

# CPU graph colors
theme[cpu_start]="{{colors.primary.default.hex}}"
theme[cpu_mid]="{{colors.secondary.default.hex}}"
theme[cpu_end]="{{colors.tertiary.default.hex}}"

# Mem graph colors
theme[free]="{{colors.primary.default.hex}}"
theme[cached]="{{colors.secondary.default.hex}}"
theme[available]="{{colors.tertiary.default.hex}}"
theme[used]="{{colors.error.default.hex}}"

# Download graph colors
theme[download_start]="{{colors.secondary.default.hex}}"
theme[download_mid]="{{colors.primary.default.hex}}"
theme[download_end]="{{colors.tertiary.default.hex}}"

# Upload graph colors
theme[upload_start]="{{colors.secondary.default.hex}}"
theme[upload_mid]="{{colors.primary.default.hex}}"
theme[upload_end]="{{colors.tertiary.default.hex}}"
